import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
    },
    extend: {
      colors: {
        // High-Contrast Precision Specification Palette
        surface: {
          DEFAULT: '#111417',
          dim: '#111417',
          bright: '#37393d',
          lowest: '#0b0e11',
          low: '#191c1f',
          container: '#1d2023',
          high: '#272a2e',
          highest: '#323538',
          card: '#1F2937',
          cardDark: '#171E2E',
          elevatedDark: '#121827',
          softLight: '#fafafa',
          strongLight: '#f5f5f5',
          tint: '#eec200',
          variant: '#323538',
        },
        'on-surface': '#e1e2e7',
        'on-surface-variant': '#d1c6ab',
        'inverse-surface': '#e1e2e7',
        'inverse-on-surface': '#2e3134',
        outline: {
          DEFAULT: '#9a9078',
          variant: '#4d4632',
        },
        primary: {
          DEFAULT: '#facc15', // Electric Amber (#facc15 / #ffecb9)
          light: '#ffecb9',
          hover: '#eec200',
          active: '#eec200',
          disabled: 'rgba(250, 204, 21, 0.4)',
          container: '#facc15',
          'on-container': '#6c5700',
          'on-primary': '#3c2f00',
          inverse: '#735c00',
          fixed: '#ffe083',
          'fixed-dim': '#eec200',
          'on-fixed': '#231b00',
          'on-fixed-variant': '#574500',
        },
        secondary: {
          DEFAULT: '#bdc7d9',
          container: '#404a59',
          'on-secondary': '#27313f',
          'on-container': '#afb9cb',
          fixed: '#d9e3f6',
          'fixed-dim': '#bdc7d9',
          'on-fixed': '#121c2a',
          'on-fixed-variant': '#3d4756',
        },
        tertiary: {
          DEFAULT: '#e6edfa',
          container: '#cad1de',
          'on-tertiary': '#2a313b',
          'on-container': '#525a64',
          fixed: '#dce3f0',
          'fixed-dim': '#c0c7d3',
          'on-fixed': '#151c25',
          'on-fixed-variant': '#404752',
        },
        error: {
          DEFAULT: '#ffb4ab',
          'on-error': '#690005',
          container: '#93000a',
          'on-container': '#ffdad6',
        },
        background: {
          DEFAULT: '#111417',
          lowest: '#0b0e11',
          secondary: '#191c1f',
          elevated: '#1F2937',
          card: '#1F2937',
        },
        'on-background': '#e1e2e7',
        'text-muted': '#9CA3AF',
        'pure-white': '#FFFFFF',

        // Legacy compatibility mappings for existing codebase elements
        status: {
          success: '#0ecb81',
          warning: '#facc15',
          error: '#ffb4ab',
        },
        text: {
          primary: '#e1e2e7',
          secondary: '#d1c6ab',
          tertiary: '#9CA3AF',
          muted: '#9CA3AF',
        },
        border: {
          DEFAULT: '#272a2e',
          hover: '#37393d',
          active: '#4d4632',
        },
        ink: '#111417',
        body: {
          DEFAULT: '#e1e2e7',
          light: '#111417',
        },
        muted: {
          DEFAULT: '#9CA3AF',
          strong: '#d1c6ab',
        },
        hairline: {
          light: '#e1e2e7',
          dark: 'rgba(255, 255, 255, 0.08)',
        },
        canvas: {
          light: '#ffffff',
          dark: '#0b0e11',
        },
        trading: {
          up: '#0ecb81',
          down: '#ffb4ab',
        },
      },
      fontFamily: {
        sans: ["'Hanken Grotesk'", "sans-serif"],
        display: ["Chivo", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        body: ["'Hanken Grotesk'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        'headline-xl': ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        'headline-lg': ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        'headline-lg-mobile': ["24px", { lineHeight: "32px", letterSpacing: "0", fontWeight: "700" }],
        'headline-md': ["24px", { lineHeight: "32px", letterSpacing: "0", fontWeight: "600" }],
        'body-lg': ["18px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "400" }],
        'body-md': ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        'body-sm': ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        'label-md': ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        'label-sm': ["12px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        // Legacy scales
        hero: ["clamp(40px, 10vw, 64px)", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        h1: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        h3: ["24px", { lineHeight: "32px", letterSpacing: "0", fontWeight: "600" }],
        body: ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        small: ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
        "2xl": "1.5rem",
        pill: "9999px",
      },
      spacing: {
        base: "4px",
        'gutter-mobile': "16px",
        'gutter-desktop': "24px",
        'margin-edge': "24px",
        'container-max': "1200px",
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        section: "80px",
      },
      boxShadow: {
        soft: "0 4px 20px -2px rgba(0, 0, 0, 0.4)",
        glow: "0 0 20px rgba(250, 204, 21, 0.2)",
        "glow-active": "0 0 30px rgba(250, 204, 21, 0.4)",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-ring": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "spin-slow": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "radar-spin": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) both",
        "pulse-ring": "pulse-ring 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "spin-slow": "spin-slow 3s linear infinite",
        "radar-spin": "radar-spin 4s linear infinite",
      },
    },
  },
  plugins: [],
};
export default config;
