/**
 * Print-shop domain — Phase 2 (real backend).
 *
 * All localStorage calls have been replaced with fetch() calls to the
 * backend API. Component-facing types are IDENTICAL to Phase 1, so
 * the components require minimal changes.
 *
 * The single source of truth is now PostgreSQL, not localStorage.
 */

// ─────────────────────────────────────────────────────────────
// Types (identical to Phase 1 — components don't change)
// ─────────────────────────────────────────────────────────────

export type UserPersona = "PRINT_SHOP" | "PERSONAL" | "EDUCATOR";

export interface PrintShopSettings {
  paymentQr: string | null;   // Pre-signed URL from R2 (read-only, generated by backend)
  bwPrice: number;
  colorPrice: number;
  locationName: string;
  isAccepting?: boolean;
}

export type PrintType = "bw" | "color";
export type PaymentStatus = "pending" | "paid" | "failed";
export type PaymentMethod = "online" | "cash";

export interface PrintJob {
  id: string;
  documentName: string;
  fileSizeBytes: number;
  fileType: string;
  pages: number;
  senderName: string;
  printType: PrintType;
  pricePerPage: number;
  totalAmount: number;
  paymentMethod: PaymentMethod;
  paymentStatus: PaymentStatus;
  paymentId: string | null;
  paidAt: string | null;
  createdAt: string;
}

// ─────────────────────────────────────────────────────────────
// API base helper
// ─────────────────────────────────────────────────────────────

const API_BASE = process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:3000/g2p/printshop';

async function apiGet<T>(path: string, token?: string): Promise<T> {
  const headers: Record<string, string> = {};
  if (token) headers['Authorization'] = `Bearer ${token}`;
  const res = await fetch(`${API_BASE}${path}`, { headers });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: 'network_error' }));
    throw new Error(err.error || 'api_error');
  }
  return res.json();
}

async function apiPost<T>(path: string, body: unknown, token?: string): Promise<T> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = `Bearer ${token}`;
  const res = await fetch(`${API_BASE}${path}`, { method: 'POST', headers, body: JSON.stringify(body) });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: 'network_error' }));
    throw new Error(err.error || 'api_error');
  }
  return res.json();
}

async function apiPut<T>(path: string, body: unknown, token?: string): Promise<T> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = `Bearer ${token}`;
  const res = await fetch(`${API_BASE}${path}`, { method: 'PUT', headers, body: JSON.stringify(body) });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: 'network_error' }));
    throw new Error(err.error || 'api_error');
  }
  return res.json();
}

async function apiPatch<T>(path: string, token: string): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    method: 'PATCH',
    headers: { 'Authorization': `Bearer ${token}` },
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: 'network_error' }));
    throw new Error(err.error || 'api_error');
  }
  return res.json();
}

// ─────────────────────────────────────────────────────────────
// Role — persisted to backend
// ─────────────────────────────────────────────────────────────

/**
/**
 * Sets the vendor's persona in the database.
 * token is the NextAuth session JWT.
 */
export async function setPersona(persona: UserPersona, _account?: string | null, token?: string): Promise<void> {
  if (!token) return;
  const vendorApiBase = process.env.NEXT_PUBLIC_API_BASE?.replace('/printshop', '') || 'http://localhost:3000/g2p/vendor';
  await fetch(`${vendorApiBase}/persona`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
    body: JSON.stringify({ persona }),
  });
}

/**
 * Returns the vendor's persona from /me response.
 * token is the NextAuth session JWT.
 */
export async function getPersona(_account?: string | null, token?: string): Promise<{ persona: UserPersona | null; persona_selected: boolean }> {
  if (!token) return { persona: null, persona_selected: false };
  try {
    const vendorApiBase = process.env.NEXT_PUBLIC_API_BASE?.replace('/printshop', '') || 'http://localhost:3000/g2p/vendor';
    const res = await fetch(`${vendorApiBase}/me`, { headers: { 'Authorization': `Bearer ${token}` }, cache: 'no-store' });
    if (!res.ok) return { persona: null, persona_selected: false };
    const data = await res.json();
    return { persona: data.persona as UserPersona ?? null, persona_selected: !!data.persona_selected };
  } catch {
    return { persona: null, persona_selected: false };
  }
}

// ─────────────────────────────────────────────────────────────
// Shop settings (student-facing: read-only, no auth)
// ─────────────────────────────────────────────────────────────

export interface PublicShopInfo {
  shopName: string;
  locationName: string | null;
  bwPrice: number;
  colorPrice: number;
  isAccepting: boolean;
  qrUrl: string | null;
}

export async function getPublicShopSettings(shopCode: string): Promise<PublicShopInfo> {
  return apiGet<PublicShopInfo>(`/shop/${shopCode}`);
}

// ─────────────────────────────────────────────────────────────
// Shop settings (shopkeeper-only, auth required)
// ─────────────────────────────────────────────────────────────

export interface ShopkeeperSettings {
  bwPrice: number;
  colorPrice: number;
  locationName: string;
  qrUrl: string | null;
  isAccepting: boolean;
}

export async function getShopSettings(token: string): Promise<ShopkeeperSettings> {
  return apiGet<ShopkeeperSettings>('/settings', token);
}

export async function saveShopSettings(
  settings: { bwPrice: number; colorPrice: number; locationName: string; isAccepting?: boolean },
  token: string
): Promise<void> {
  await apiPut('/settings', settings, token);
}

export async function uploadQrImage(file: File, token: string): Promise<{ qrUrl: string }> {
  const arrayBuffer = await file.arrayBuffer();
  const res = await fetch(`${API_BASE}/settings/qr`, {
    method: 'PUT',
    headers: {
      'Content-Type': file.type,
      'Authorization': `Bearer ${token}`,
    },
    body: arrayBuffer,
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: 'upload_failed' }));
    throw new Error(err.error || 'upload_failed');
  }
  return res.json();
}

// ─────────────────────────────────────────────────────────────
// Print Jobs — student submission
// ─────────────────────────────────────────────────────────────

export interface SubmitJobArgs {
  shopCode: string;
  senderName: string;
  documentName: string;
  fileSizeBytes: number;
  fileType: string;
  pages: number;
  printType: PrintType;
  paymentMethod: PaymentMethod;
}

export interface SubmitJobResult {
  jobId: string;
  totalAmount: number;
  pricePerPage: number;
  createdAt: string;
}

export async function submitPrintJob(args: SubmitJobArgs): Promise<SubmitJobResult> {
  return apiPost<SubmitJobResult>('/jobs', args);
}

// ─────────────────────────────────────────────────────────────
// Print Jobs — shopkeeper operations
// ─────────────────────────────────────────────────────────────

export async function getPrintJobs(
  token: string,
  filters: { status?: string; method?: string; printType?: string; limit?: number; offset?: number } = {}
): Promise<PrintJob[]> {
  const params = new URLSearchParams();
  if (filters.status)    params.set('status', filters.status);
  if (filters.method)    params.set('method', filters.method);
  if (filters.printType) params.set('printType', filters.printType);
  if (filters.limit)     params.set('limit', String(filters.limit));
  if (filters.offset)    params.set('offset', String(filters.offset));
  const query = params.toString() ? `?${params.toString()}` : '';
  const data = await apiGet<{ jobs: any[] }>(`/jobs${query}`, token);
  return data.jobs.map(normalizeJob);
}

function normalizeJob(j: Record<string, unknown>): PrintJob {
  return {
    id: j.id as string,
    documentName: (j.document_name ?? j.documentName) as string,
    fileSizeBytes: Number(j.file_size_bytes ?? j.fileSizeBytes),
    fileType: (j.file_type ?? j.fileType) as string,
    pages: Number(j.pages),
    senderName: (j.sender_name ?? j.senderName) as string,
    printType: (j.print_type ?? j.printType) as PrintType,
    pricePerPage: parseFloat(String(j.price_per_page ?? j.pricePerPage)),
    totalAmount: parseFloat(String(j.total_amount ?? j.totalAmount)),
    paymentMethod: (j.payment_method ?? j.paymentMethod) as PaymentMethod,
    paymentStatus: (j.payment_status ?? j.paymentStatus) as PaymentStatus,
    paymentId: (j.payment_id ?? j.paymentId) as string | null,
    paidAt: (j.paid_at ?? j.paidAt) as string | null,
    createdAt: (j.created_at ?? j.createdAt) as string,
  };
}

export async function confirmJobPayment(jobId: string, token: string): Promise<{ paymentId: string }> {
  return apiPatch<{ paymentId: string }>(`/jobs/${jobId}/confirm`, token);
}

export async function markJobFailed(jobId: string, token: string): Promise<void> {
  await apiPatch(`/jobs/${jobId}/fail`, token);
}

// ─────────────────────────────────────────────────────────────
// Analytics
// ─────────────────────────────────────────────────────────────

export interface PrintShopKpis {
  totalDocuments: number;
  paidDocuments: number;
  pendingPayments: number;
  totalRevenue: number;
  colorPrints: number;
  bwPrints: number;
}

export async function getAnalytics(token: string): Promise<{ kpis: PrintShopKpis; revenueSeries: { date: string; revenue: number }[] }> {
  return apiGet('/analytics', token);
}

// ─────────────────────────────────────────────────────────────
// Computed analytics (kept for PaymentsPanel CSV export)
// ─────────────────────────────────────────────────────────────

export function computeKpis(jobs: PrintJob[]): PrintShopKpis {
  const paid = jobs.filter((j) => j.paymentStatus === "paid");
  return {
    totalDocuments: jobs.length,
    paidDocuments: paid.length,
    pendingPayments: jobs.filter((j) => j.paymentStatus === "pending").length,
    totalRevenue: paid.reduce((sum, j) => sum + j.totalAmount, 0),
    colorPrints: paid.filter((j) => j.printType === "color").length,
    bwPrints: paid.filter((j) => j.printType === "bw").length,
  };
}

export type RevenueRange = "daily" | "weekly" | "monthly";

export function revenueSeries(jobs: PrintJob[], range: RevenueRange): { label: string; revenue: number }[] {
  const paid = jobs.filter((j) => j.paymentStatus === "paid" && j.paidAt);
  const now = new Date();
  const buckets: { label: string; from: Date; to: Date }[] = [];

  if (range === "daily") {
    for (let i = 6; i >= 0; i--) {
      const d = new Date(now); d.setDate(now.getDate() - i);
      const from = new Date(d); from.setHours(0, 0, 0, 0);
      const to = new Date(d); to.setHours(23, 59, 59, 999);
      buckets.push({ label: d.toLocaleDateString("en-IN", { weekday: "short" }), from, to });
    }
  } else if (range === "weekly") {
    for (let i = 7; i >= 0; i--) {
      const to = new Date(now); to.setDate(now.getDate() - i * 7);
      const from = new Date(to); from.setDate(to.getDate() - 6);
      buckets.push({ label: `W${8 - i}`, from, to });
    }
  } else {
    for (let i = 5; i >= 0; i--) {
      const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
      const from = d;
      const to = new Date(d.getFullYear(), d.getMonth() + 1, 0, 23, 59, 59);
      buckets.push({ label: d.toLocaleDateString("en-IN", { month: "short" }), from, to });
    }
  }

  return buckets.map((b) => ({
    label: b.label,
    revenue: paid
      .filter((j) => {
        const t = new Date(j.paidAt as string).getTime();
        return t >= b.from.getTime() && t <= b.to.getTime();
      })
      .reduce((s, j) => s + j.totalAmount, 0),
  }));
}

// ─────────────────────────────────────────────────────────────
// Formatting helpers (unchanged from Phase 1)
// ─────────────────────────────────────────────────────────────

export const inr = (n: number) => `₹${n.toLocaleString("en-IN")}`;

export function formatBytes(bytes: number): string {
  if (bytes === 0) return "0 B";
  const k = 1024;
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${["B", "KB", "MB", "GB"][i]}`;
}

// ─────────────────────────────────────────────────────────────
// DEFAULT_SETTINGS shim (used in PrintFlow initial state)
// ─────────────────────────────────────────────────────────────

export const DEFAULT_SETTINGS: ShopkeeperSettings = {
  bwPrice: 2,
  colorPrice: 5,
  locationName: "",
  qrUrl: null,
  isAccepting: true,
};
