/**
 * Print-shop domain — Phase 2 (real backend).
 *
 * All localStorage calls have been replaced with fetch() calls to the
 * backend API. Component-facing types are IDENTICAL to Phase 1, so
 * the components require minimal changes.
 *
 * The single source of truth is now PostgreSQL, not localStorage.
 */

// ─────────────────────────────────────────────────────────────
// Types (identical to Phase 1 — components don't change)
// ─────────────────────────────────────────────────────────────

export type UserPersona = "PRINT_SHOP" | "PERSONAL" | "EDUCATOR";

export interface PrintShopSettings {
  paymentQr: string | null;   // Pre-signed URL from R2 (read-only, generated by backend)
  bwPrice: number;
  colorPrice: number;
  locationName: string;
  isAccepting?: boolean;
}

export type PrintType = "bw" | "color";
export type PaymentStatus = "pending" | "paid" | "failed";
export type PaymentMethod = "online" | "cash";

export interface PrintConfig {
  copies: number;       // 1–20
  doubleSided: boolean;
  stapling: boolean;
  paperSize: 'A4' | 'A3';
}

export interface PrintJob {
  id: string;
  documentName: string;
  fileSizeBytes: number;
  fileType: string;
  pages: number;
  senderName: string;
  printType: PrintType;
  pricePerPage: number;
  totalAmount: number;
  paymentMethod: PaymentMethod;
  paymentStatus: PaymentStatus;
  paymentId: string | null;
  paidAt: string | null;
  createdAt: string;
  printConfig?: PrintConfig | null;
  jobStatus?: 'queued' | 'printing' | 'printed' | 'cancelled';
  printedAt?: string | null;
  razorpayOrderId?: string | null;
  amountPaise?: number;
  fileUrl?: string | null;
  deletedAt?: string | null;
}

// ─────────────────────────────────────────────────────────────
// API base helper
// ─────────────────────────────────────────────────────────────

const EXPRESS_BACKEND_URL = process.env.NEXT_PUBLIC_EXPRESS_URL || process.env.NEXT_PUBLIC_EXPRESS_BACKEND_URL || process.env.NEXT_PUBLIC_SIGNAL_URL || process.env.NEXT_PUBLIC_BACKEND_URL || "https://share2me-version-2-0.onrender.com";
const API_BASE = process.env.NEXT_PUBLIC_API_BASE || `${EXPRESS_BACKEND_URL}/g2p/printshop`;

async function apiGet<T>(path: string, token?: string): Promise<T> {
  const headers: Record<string, string> = {};
  if (token) headers['Authorization'] = `Bearer ${token}`;
  const separator = path.includes('?') ? '&' : '?';
  const url = `${API_BASE}${path}${separator}_t=${Date.now()}`;
  const res = await fetch(url, { headers, cache: 'no-store' });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: 'network_error' }));
    throw new Error(err.error || 'api_error');
  }
  return res.json();
}

async function apiPost<T>(path: string, body: unknown, token?: string): Promise<T> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = `Bearer ${token}`;
  const res = await fetch(`${API_BASE}${path}`, { method: 'POST', headers, body: JSON.stringify(body), cache: 'no-store' });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: 'network_error' }));
    throw new Error(err.error || 'api_error');
  }
  return res.json();
}

async function apiPut<T>(path: string, body: unknown, token?: string): Promise<T> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = `Bearer ${token}`;
  const res = await fetch(`${API_BASE}${path}`, { method: 'PUT', headers, body: JSON.stringify(body), cache: 'no-store' });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: 'network_error' }));
    throw new Error(err.error || 'api_error');
  }
  return res.json();
}

async function apiPatch<T>(path: string, token: string): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    method: 'PATCH',
    headers: { 'Authorization': `Bearer ${token}` },
    cache: 'no-store',
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: 'network_error' }));
    throw new Error(err.error || 'api_error');
  }
  return res.json();
}

// ─────────────────────────────────────────────────────────────
// Role — persisted to backend
// ─────────────────────────────────────────────────────────────

/**
/**
 * Sets the vendor's persona in the database.
 * token is the NextAuth session JWT.
 */
export async function setPersona(persona: UserPersona, account?: string | null, token?: string): Promise<void> {
  // Write to localStorage immediately so reloads don't re-show the modal
  // even if the backend call hasn't completed yet.
  if (typeof window !== 'undefined' && account) {
    try {
      localStorage.setItem(`g2p_persona_${account}`, JSON.stringify({ persona, selected: true }));
    } catch { /* quota exceeded — ignore */ }
  }
  if (!token) return;
  const vendorApiBase = process.env.NEXT_PUBLIC_API_BASE?.replace('/printshop', '') || `${EXPRESS_BACKEND_URL}/g2p/vendor`;
  await fetch(`${vendorApiBase}/persona`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
    body: JSON.stringify({ persona }),
  });
}

/**
 * Returns the vendor's persona from /me response.
 * token is the NextAuth session JWT.
 */
export async function getPersona(account?: string | null, token?: string): Promise<{ persona: UserPersona | null; persona_selected: boolean }> {
  // Fast path: localStorage cache keyed by account email.
  // Written by setPersona() the moment the user picks a role, so reloads
  // never re-show the modal even when the backend is slow/unavailable.
  if (typeof window !== 'undefined' && account) {
    try {
      const cached = localStorage.getItem(`g2p_persona_${account}`);
      if (cached) {
        const parsed = JSON.parse(cached) as { persona: UserPersona; selected: boolean };
        if (parsed.selected && parsed.persona) {
          return { persona: parsed.persona, persona_selected: true };
        }
      }
    } catch { /* corrupt entry — fall through to backend */ }
  }

  if (!token) return { persona: null, persona_selected: false };
  try {
    const vendorApiBase = process.env.NEXT_PUBLIC_API_BASE?.replace('/printshop', '') || `${EXPRESS_BACKEND_URL}/g2p/vendor`;
    const res = await fetch(`${vendorApiBase}/me`, { headers: { 'Authorization': `Bearer ${token}` }, cache: 'no-store' });
    if (!res.ok) return { persona: null, persona_selected: false };
    const data = await res.json();
    const persona = data.persona as UserPersona ?? null;
    const persona_selected = !!data.persona_selected;

    // Backfill localStorage if backend says selected=true (e.g. first load after
    // a different device or after clearing storage).
    if (persona_selected && persona && typeof window !== 'undefined' && account) {
      try {
        localStorage.setItem(`g2p_persona_${account}`, JSON.stringify({ persona, selected: true }));
      } catch { /* ignore */ }
    }

    return { persona, persona_selected };
  } catch {
    return { persona: null, persona_selected: false };
  }
}

// ─────────────────────────────────────────────────────────────
// Shop settings (student-facing: read-only, no auth)
// ─────────────────────────────────────────────────────────────

export interface PublicShopInfo {
  shopName: string;
  locationName: string | null;
  bwPrice: number;
  colorPrice: number;
  isAccepting: boolean;
  qrUrl: string | null;         // Razorpay auto-QR image URL
  charges_enabled?: boolean;    // true when vendor has connected UPI/Razorpay
  isPrintShop?: boolean;        // true when vendor persona === 'PRINT_SHOP'
  upiId?: string | null;
  upiName?: string | null;
}

export async function getPublicShopSettings(shopCode: string): Promise<PublicShopInfo> {
  return apiGet<PublicShopInfo>(`/shop/${shopCode}`);
}

// ─────────────────────────────────────────────────────────────
// Shop settings (shopkeeper-only, auth required)
// ─────────────────────────────────────────────────────────────

export interface ShopkeeperSettings {
  bwPrice: number;
  colorPrice: number;
  locationName: string;
  qrUrl: string | null;
  isAccepting: boolean;
  razorpay_account_id?: string | null;
  charges_enabled?: boolean;
  upiId?: string;
  upiName?: string;
  qrImageUrl?: string | null;  // Razorpay QR image URL (permanent)
  qrId?: string | null;        // Razorpay QR Code ID
  retentionHours?: number;
  latitude?: number | null;
  longitude?: number | null;
}

export async function getShopSettings(token: string): Promise<ShopkeeperSettings> {
  return apiGet<ShopkeeperSettings>('/settings', token);
}

export async function saveShopSettings(
  settings: { bwPrice: number; colorPrice: number; locationName: string; isAccepting?: boolean; razorpay_account_id?: string | null; charges_enabled?: boolean; retentionHours?: number },
  token: string
): Promise<void> {
  await apiPut('/settings', settings, token);
}

export async function saveShopLocation(lat: number, lng: number, token: string): Promise<{ success: boolean; location_updated_at: string }> {
  return apiPut('/settings/location', { lat, lng }, token);
}

export async function uploadQrImage(file: File, token: string): Promise<{ qrUrl: string }> {
  const arrayBuffer = await file.arrayBuffer();
  const res = await fetch(`${API_BASE}/settings/qr`, {
    method: 'PUT',
    headers: {
      'Content-Type': file.type,
      'Authorization': `Bearer ${token}`,
    },
    body: arrayBuffer,
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: 'upload_failed' }));
    throw new Error(err.error || 'upload_failed');
  }
  return res.json();
}

export interface BillingStatus {
  charges_enabled: boolean;
  razorpay_account_id: string | null;
  bank_last4: string | null;
  bank_verification_status: 'pending' | 'verified' | 'failed';
  upi_id?: string | null;
  upi_name?: string | null;
}

export async function getBillingStatus(token: string): Promise<BillingStatus> {
  const res = await fetch(`${API_BASE.replace('/printshop', '')}/billing/status`, {
    method: 'GET',
    headers: { 'Authorization': `Bearer ${token}` },
    cache: 'no-store'
  });
  if (!res.ok) throw new Error('Failed to fetch billing status');
  return res.json();
}

export async function requestBankOtp(token: string): Promise<{ success: boolean; message: string }> {
  const res = await fetch(`${API_BASE.replace('/printshop', '')}/billing/bank/request-edit`, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${token}` },
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ message: 'Failed to request OTP' }));
    throw new Error(err.message || 'OTP request failed');
  }
  return res.json();
}

export async function verifyBankOtp(otp: string, token: string): Promise<{ success: boolean; editToken: string }> {
  const res = await fetch(`${API_BASE.replace('/printshop', '')}/billing/bank/verify-otp`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify({ otp })
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ message: 'Failed to verify OTP' }));
    throw new Error(err.message || 'OTP verification failed');
  }
  return res.json();
}

export async function updateUpiDetails(
  editToken: string,
  upiId: string,
  upiName: string,
  token: string
): Promise<{ success: boolean; upi_id: string; status: string }> {
  const res = await fetch(`${API_BASE.replace('/printshop', '')}/billing/upi/update`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify({ editToken, upiId, upiName })
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ message: 'Failed to update UPI details' }));
    throw new Error(err.message || 'UPI update failed');
  }
  return res.json();
}

// ─────────────────────────────────────────────────────────────
// Print Jobs — student submission
// ─────────────────────────────────────────────────────────────

export interface SubmitJobArgs {
  shopCode: string;
  senderName: string;
  documentName: string;
  fileSizeBytes: number;
  fileType: string;
  pages: number;
  printType: PrintType;
  paymentMethod: PaymentMethod;
  printConfig?: PrintConfig;
}

export interface SubmitJobResult {
  jobId: string;
  totalAmount: number;
  pricePerPage: number;
  createdAt: string;
  stripeCheckoutUrl?: string;
  razorpayOrderId?: string;
  amountPaise?: number;
  uploadUrl: string;
}

export async function submitPrintJob(args: SubmitJobArgs): Promise<SubmitJobResult> {
  return apiPost<SubmitJobResult>('/jobs', args);
}

export interface SubmitBulkJobArgs {
  shopCode: string;
  senderName: string;
  paymentMethod: PaymentMethod;
  printType: PrintType;
  files: {
    documentName: string;
    fileSizeBytes: number;
    fileType: string;
    pages: number;
    printConfig?: PrintConfig;
  }[];
}

export interface SubmitBulkJobResult {
  jobs: {
    jobId: string;
    uploadUrl: string;
    totalAmount: number;
    pricePerPage: number;
    createdAt: string;
  }[];
  totalBatchAmount: number;
  razorpayOrderId?: string | null;
  amountPaise?: number;
}

export async function submitBulkPrintJob(args: SubmitBulkJobArgs): Promise<SubmitBulkJobResult> {
  return apiPost<SubmitBulkJobResult>('/jobs/bulk', args);
}

// ─────────────────────────────────────────────────────────────
// Print Jobs — shopkeeper operations
// ─────────────────────────────────────────────────────────────

export async function getPrintJobs(
  token: string,
  filters: { status?: string; method?: string; printType?: string; limit?: number; offset?: number } = {}
): Promise<PrintJob[]> {
  const params = new URLSearchParams();
  if (filters.status)    params.set('status', filters.status);
  if (filters.method)    params.set('method', filters.method);
  if (filters.printType) params.set('printType', filters.printType);
  if (filters.limit)     params.set('limit', String(filters.limit));
  if (filters.offset)    params.set('offset', String(filters.offset));
  const query = params.toString() ? `?${params.toString()}` : '';
  const data = await apiGet<{ jobs: any[] }>(`/jobs${query}`, token);
  return data.jobs.map(normalizeJob);
}

function normalizeJob(j: Record<string, unknown>): PrintJob {
  return {
    id: j.id as string,
    documentName: (j.document_name ?? j.documentName) as string,
    fileSizeBytes: Number(j.file_size_bytes ?? j.fileSizeBytes),
    fileType: (j.file_type ?? j.fileType) as string,
    pages: Number(j.pages),
    senderName: (j.sender_name ?? j.senderName) as string,
    printType: (j.print_type ?? j.printType) as PrintType,
    pricePerPage: parseFloat(String(j.price_per_page ?? j.pricePerPage)),
    totalAmount: parseFloat(String(j.total_amount ?? j.totalAmount)),
    paymentMethod: (j.payment_method ?? j.paymentMethod) as PaymentMethod,
    paymentStatus: (j.payment_status ?? j.paymentStatus) as PaymentStatus,
    paymentId: (j.payment_id ?? j.paymentId) as string | null,
    paidAt: (j.paid_at ?? j.paidAt) as string | null,
    createdAt: (j.created_at ?? j.createdAt) as string,
    deletedAt: (j.deleted_at ?? j.deletedAt) as string | null,
    printConfig: (typeof j.print_config === 'string' ? JSON.parse(j.print_config) : j.print_config) as PrintConfig | undefined,
    jobStatus: (j.job_status ?? j.jobStatus) as PrintJob['jobStatus'] ?? 'queued',
    printedAt: (j.printed_at ?? j.printedAt) as string | null ?? null,
  };
}

export async function confirmJobPayment(jobId: string, token: string): Promise<{ paymentId: string }> {
  return apiPatch<{ paymentId: string }>(`/jobs/${jobId}/confirm`, token);
}

export async function markJobPrinted(jobId: string, token: string, printConfig?: PrintConfig): Promise<{ printedAt: string }> {
  const res = await fetch(`${API_BASE}/jobs/${jobId}/print`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
    body: JSON.stringify(printConfig ? { printConfig } : {}),
    cache: 'no-store',
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: 'api_error' }));
    throw new Error(err.error || 'mark_printed_failed');
  }
  return res.json();
}

export async function markJobFailed(jobId: string, token: string): Promise<void> {
  await apiPatch(`/jobs/${jobId}/fail`, token);
}

export async function updatePrintConfig(jobId: string, config: Partial<PrintConfig>, token: string): Promise<void> {
  const res = await fetch(`${API_BASE}/jobs/${jobId}/config`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`
    },
    body: JSON.stringify({ config })
  });
  if (!res.ok) throw new Error('failed_to_update_config');
}

// ─────────────────────────────────────────────────────────────
// Agent Dashboard Integration
// ─────────────────────────────────────────────────────────────

export async function getAgentPrinters(token: string): Promise<{ printers: string[]; online: boolean }> {
  return apiGet<{ printers: string[]; online: boolean }>('/printers', token);
}

export async function batchPrint(jobIds: string[], printerName: string, token: string): Promise<{ success: boolean; count: number }> {
  return apiPost<{ success: boolean; count: number }>('/print-batch', { jobIds, printerName }, token);
}

export async function getAgentToken(token: string): Promise<{ token: string }> {
  return apiPost<{ token: string }>('/agent-token', {}, token);
}

// ─────────────────────────────────────────────────────────────
// Analytics
// ─────────────────────────────────────────────────────────────

export interface PrintShopKpis {
  totalDocuments: number;
  paidDocuments: number;
  pendingPayments: number;
  totalRevenue: number;
  colorPrints: number;
  bwPrints: number;
}

export async function getAnalytics(token: string): Promise<{ kpis: PrintShopKpis; revenueSeries: { date: string; revenue: number }[] }> {
  return apiGet('/analytics', token);
}

// ─────────────────────────────────────────────────────────────
// Computed analytics (kept for PaymentsPanel CSV export)
// ─────────────────────────────────────────────────────────────

export function computeKpis(jobs: PrintJob[]): PrintShopKpis {
  const paid = jobs.filter((j) => j.paymentStatus === "paid");
  return {
    totalDocuments: jobs.length,
    paidDocuments: paid.length,
    pendingPayments: jobs.filter((j) => j.paymentStatus === "pending").length,
    totalRevenue: paid.reduce((sum, j) => sum + j.totalAmount, 0),
    colorPrints: paid.filter((j) => j.printType === "color").length,
    bwPrints: paid.filter((j) => j.printType === "bw").length,
  };
}

export type RevenueRange = "daily" | "weekly" | "monthly" | "all_time";

export function filterJobsByRange(jobs: PrintJob[], range: RevenueRange): PrintJob[] {
  const now = new Date();
  let cutoff = new Date(now);
  if (range === "daily") {
    cutoff.setDate(now.getDate() - 6);
    cutoff.setHours(0, 0, 0, 0);
  } else if (range === "weekly") {
    cutoff.setDate(now.getDate() - 7 * 7 - 6);
    cutoff.setHours(0, 0, 0, 0);
  } else if (range === "monthly") {
    cutoff = new Date(now.getFullYear(), now.getMonth() - 5, 1);
  } else {
    // all_time - return everything
    return jobs;
  }
  return jobs.filter(j => {
    const d = new Date(j.paidAt || j.createdAt).getTime();
    return d >= cutoff.getTime();
  });
}

export function revenueSeries(jobs: PrintJob[], range: RevenueRange): { label: string; revenue: number }[] {
  const paid = jobs.filter((j) => j.paymentStatus === "paid" && j.paidAt);
  const now = new Date();
  const buckets: { label: string; from: Date; to: Date }[] = [];

  if (range === "daily") {
    for (let i = 6; i >= 0; i--) {
      const d = new Date(now); d.setDate(now.getDate() - i);
      const from = new Date(d); from.setHours(0, 0, 0, 0);
      const to = new Date(d); to.setHours(23, 59, 59, 999);
      buckets.push({ label: d.toLocaleDateString("en-IN", { weekday: "short" }), from, to });
    }
  } else if (range === "weekly") {
    for (let i = 7; i >= 0; i--) {
      const to = new Date(now);
      to.setDate(now.getDate() - i * 7);
      to.setHours(23, 59, 59, 999);
      
      const from = new Date(now);
      from.setDate(now.getDate() - i * 7 - 6);
      from.setHours(0, 0, 0, 0);
      
      buckets.push({ label: `W${8 - i}`, from, to });
    }
  } else if (range === "monthly") {
    for (let i = 5; i >= 0; i--) {
      const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
      const from = d;
      const to = new Date(d.getFullYear(), d.getMonth() + 1, 0, 23, 59, 59);
      buckets.push({ label: d.toLocaleDateString("en-IN", { month: "short" }), from, to });
    }
  } else if (range === "all_time") {
    // For all time, we group by month but dynamically based on the oldest job
    if (paid.length === 0) {
      buckets.push({ label: now.toLocaleDateString("en-IN", { month: "short", year: "2-digit" }), from: new Date(0), to: now });
    } else {
      const oldest = new Date(Math.min(...paid.map(j => new Date(j.paidAt as string).getTime())));
      let current = new Date(oldest.getFullYear(), oldest.getMonth(), 1);
      while (current <= now) {
        const from = new Date(current);
        const to = new Date(current.getFullYear(), current.getMonth() + 1, 0, 23, 59, 59);
        buckets.push({ label: current.toLocaleDateString("en-IN", { month: "short", year: "2-digit" }), from, to });
        current.setMonth(current.getMonth() + 1);
      }
    }
  }

  return buckets.map((b) => ({
    label: b.label,
    revenue: paid
      .filter((j) => {
        const t = new Date(j.paidAt as string).getTime();
        return t >= b.from.getTime() && t <= b.to.getTime();
      })
      .reduce((s, j) => s + j.totalAmount, 0),
  }));
}

// ─────────────────────────────────────────────────────────────
// Formatting helpers (unchanged from Phase 1)
// ─────────────────────────────────────────────────────────────

export const inr = (n: number) => `₹${n.toLocaleString("en-IN")}`;

export function formatBytes(bytes: number): string {
  if (bytes === 0) return "0 B";
  const k = 1024;
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${["B", "KB", "MB", "GB"][i]}`;
}

// ─────────────────────────────────────────────────────────────
// DEFAULT_SETTINGS shim (used in PrintFlow initial state)
// ─────────────────────────────────────────────────────────────

export const DEFAULT_SETTINGS: ShopkeeperSettings = {
  bwPrice: 2,
  colorPrice: 5,
  locationName: "",
  qrUrl: null,
  isAccepting: true,
  upiId: '',
  upiName: ''
};
